gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to rest your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your POKéMON\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"

gText_AreYouARookieTrainer:: 
    .string "Hello, and welcome to\n"
    .string "the Pokémon Center.\p"
    .string "We restore your tired Pokémon\n"
    .string "to full health.\p"
    .string "This is your first time here,\n"
    .string "isn't it?\p"
    .string "It's your lucky day!\p"
    .string "We're  giving out fully loaded\n"
    .string "Picnic Baskets to all rookie Trainers.\p"
    .string "Here, take one!$"

gText_ExplainPokeVial:: 
    .string "That basket contains very healthy,\n"
    .string "hearty Pokémon snacks.\p"
    .string "It's enough of a pick-me-up to heal\n"
    .string "your entire party when you stop to\l"
	.string "have a picnic, but you can't use it\l"
	.string "in battles.\p"
    .string "There's only enough space to fit two\n"
    .string "meals, but we'll refill it for you\l"
    .string "every time you heal up at a Pokémon\l"
    .string "Center for free.\p"
    .string "It's like a portable Pokémon Center!\p"
    .string "Now, let's give your Pokemon a rest.$"
